server:
  port: 9000

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

      routes:
        - id: sds-identity-provider
          uri: http://localhost:9030
          predicates:
            - Path=/identity-provider/**
          filters:
            - RewritePath=/identity-provider,/
            - GatewayAuthorizationFilter

        - id: sds-back-office
          uri: http://localhost:8080
          predicates:
            - Path=/back-office/**
          filters:
            - GatewayAuthorizationFilter

        - id: sds-front-office
          uri: http://localhost:8080
          predicates:
            - Path=/front-office/**
          filters:
            - GatewayAuthorizationFilter